### ISSUE TITLE
C:\Users\keith\

### ISSUE THREAD

**Issue by Birdseye232** [UXabre/WIMan#1]
after running ".\GenerateWIM.ps1" i get this.
Where does this C:\Users\keith comes from? i have no such user.

windows-adk-winpe v10.0.18362.1 [Approved]
windows-adk-winpe package files install completed. Performing other installation steps.
File appears to be downloaded already. Verifying with package checksum to determine if it needs to be redownloaded.
Hashes match.
Hashes match.
Installing Windows Assessment and Deployment Kit...
ERROR: Running ["C:\Users\xxxxxxx\AppData\Local\Temp\chocolatey\windows-adk-winpe\10.0.18362.1\adkwinpesetup.exe" /quiet /norestart /log C:\Users\keith\AppData\Local\Temp\winPE_adk.log /features + /installPath C:\foreman_win\WIMan-master\.tmp\wadk-winpe"] was not successful. Exit code was '1001'. See log for possible error messages.
The install of windows-adk-winpe was NOT successful.

**Comment by UXabre** [comment]
Hello @Birdseye232,


I think "keith" is the user that created the windows-adk-winpe package in choco; normally this shouldn't be an issue (Although it's not "clean" of the original package author)... Can you share the content of "C:\Users\keith\AppData\Local\Temp\winPE_adk.log" I think the system creates this folder automatically though... if not, could you perhaps create the folder structure manually and re-run the script?

To exclude one thing: did you run the script as administrator?


Kind regards,
Arend

**Comment by Birdseye232** [comment]
i figured out that i already had aik installed on my win10 machine and i saw this in one of the log files. it complained about this fact. i ran the whole thing on a different machine and it worked.
