### ISSUE TITLE
ad domain join

### ISSUE THREAD

**Issue by m4c3** [UXabre/WIMan#6]
Hi,
im not sure if the ad domain join works.
In Script template "Windows peSetup.cmd"  we download a script 
```
<% if foreman_url('user_data') %>
echo Downloading user data
%WGET% <%= foreman_url('user_data') %> -O c:\deploy\joinDomain.ps1
<% end -%>
```

but for what does user_data stand for? in the templates shipped with foreman 2.1 i didnt found anything that joins a computer to a domain..

thanks
Matthias

**Comment by UXabre** [comment]
Hi @m4c3,

To be honest, I haven't actually tried this yet, I just based part of my work (mainly the foreman scripts) on the WIMaging effort done earlier:
https://github.com/helge000/foreman-wimaging/tree/fa253b57e0a0ff1494801414cf3cae0125bd460e/wimaging

I personally don't have a situation where I deploy an AD environment..yet


Kr

**Comment by m4c3** [comment]
Hi, okay ill open a issue in foreman redmine this.
i think best would be to directly include the domain join part in the template "Windows peSetup.cmd" 
bye matthias

**Comment by m4c3** [comment]
ive created https://github.com/theforeman/foreman/pull/7898 as a followup
